catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import CatalogTemplateView, ProductDetailView, ProductListView, ContactCreateView, BlogListView, \
    BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

app_name = 'catalog'

urlpatterns = [
    path('', CatalogTemplateView.as_view(), name='index'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('contacts/', ContactCreateView.as_view(), name='contacts'),
    path('blog/', BlogListView.as_view(), name='blog'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path('create/product/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('category', CategoryListView.as_view(), name='category'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, NewPasswordView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
    path('password-reset/', NewPasswordView.as_view(), name='password_reset'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
]

catalog/models.py
from django.db import models, connection

NULLABLE = {"null": True, "blank": True}


class Product(models.Model):
    # Таблица товаров
    name = models.CharField(
        max_length=100, verbose_name="Название", help_text="Введите название товара"
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание товара", **NULLABLE
    )
    image = models.ImageField(upload_to="products/", verbose_name="Фото", **NULLABLE)
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name="Категория",
        related_name="products",
    )
    price = models.IntegerField(verbose_name="Цена", help_text="Введите цену товара")
    created_at = models.DateTimeField(
        verbose_name="Дата создания",
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name="Дата изменения",
        auto_now=True,
    )
    owner = models.ForeignKey(
        'users.User',
        on_delete=models.SET_NULL,
        **NULLABLE,
        verbose_name="Владелец",
        related_name="products",
    )
    is_published = models.BooleanField(default=False, verbose_name="публикация")

    def __str__(self):
        return f"{self.name} ({self.category}) - {self.price} руб."

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name"]
        permissions = [
            ("can_edit_publication", "Может отменять публикацию продукта"),
            ("can_edit_description", "Может редактировать описание продукта"),
            ("can_edit_category", "Может менять категорию любого продукта"),
        ]


class Category(models.Model):
    # Таблица категорий
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование",
        help_text="Введите название категории",
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Введите описание категории", **NULLABLE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Version(models.Model):
    # Таблица версий
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="versions", verbose_name="Продукт")
    version_number = models.IntegerField(verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_active = models.BooleanField(default=True, verbose_name="Активная версия")

    def __str__(self):
        return f"{self.product} - {self.version_name} ({self.version_number})"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["-version_number"]


class Contact(models.Model):
    # Таблица контактов и сообщений
    name = models.CharField(max_length=100, verbose_name="Имя")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    message = models.TextField(verbose_name="Сообщение")
    created_at = models.DateTimeField(
        verbose_name="Дата создания",
        auto_now_add=True,
    )

    def __str__(self):
        return f"{self.name} ({self.phone})"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["-created_at"]


class Blog(models.Model):
    # Таблица для блога
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = models.CharField(max_length=50, verbose_name="Слаг", **NULLABLE)
    text = models.TextField(verbose_name="Текст")
    preview = models.ImageField(upload_to="blog/", verbose_name="Превью", **NULLABLE)
    created_at = models.DateTimeField(
        verbose_name="Дата создания",
        auto_now_add=True,
    )
    publication = models.BooleanField(default=True, verbose_name="Опубликовано")
    number_of_views = models.IntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return f'{self.title} - {self.created_at}'

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-created_at"]

catalog/forms.py
from django import forms
from django.forms import BooleanField
from catalog.models import Product, Version


class StyleFormMixin:
    """Добавляет классы к виджетам формы для стилизации."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'is_published', 'category')


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_keywords = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                          'радар']

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
        }

    def clean_name(self):
        clean_data = self.cleaned_data['name']
        if any(keyword in clean_data for keyword in self.forbidden_keywords):
            raise forms.ValidationError('Это название содержит запрещенные слова.')
        return clean_data

    def clean_description(self):
        clean_data = self.cleaned_data['description']
        if any(keyword in clean_data for keyword in self.forbidden_keywords):
            raise forms.ValidationError('Описание содержит запрещенные слова.')
        return clean_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'
        widgets = {
            'product': forms.Select(attrs={'class': 'form-control'}),
            'version': forms.TextInput(attrs={'class': 'form-control'}),
            'release_date': forms.DateInput(attrs={'class': 'form-control'}),
        }

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.text import slugify

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Contact, Blog, Version, Category
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.services import get_categories_from_cache


class ProductFormsetMixin:
    """Миксин для формсета продуктов"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        ProductFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.POST:
            context['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context['formset'] = ProductFormset(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class ProductVersionMixin:
    """Миксин для добавления активной версии продукта в контекст."""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if isinstance(self, ListView):
            products = context.get('object_list', [])
            for product in products:
                version = Version.objects.filter(product=product, is_active=True).last()
                product.active_version = version.version_name if version else 'Нет активной версии'
        elif isinstance(self, DetailView):
            product = context.get('product')
            if product:
                version = Version.objects.filter(product=product, is_active=True).last()
                product.active_version = version.version_name if version else 'Нет активной версии'
        return context


class CategoryListView(ListView):
    """Список категорий."""
    model = Category

    def get_queryset(self):
        return get_categories_from_cache()


class ProductListView(ProductVersionMixin, ListView):
    """Список продуктов."""
    model = Product


class ProductDetailView(DetailView):
    """Подробная информация о продукте."""
    model = Product


class ProductCreateView(LoginRequiredMixin, ProductFormsetMixin, CreateView):
    """Добавление нового продукта."""
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:products')
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def form_valid(self, form):
        # Метод для связывания продукта с пользователем
        product = form.save(commit=False)
        product.owner = self.request.user  # Присваиваем владельца продукта
        product.save()
        return redirect('catalog:product_detail', pk=product.pk)


class ProductUpdateView(LoginRequiredMixin, ProductFormsetMixin, UpdateView):
    """Редактирование продукта."""
    model = Product
    form_class = ProductForm
    template_name = 'catalog/product_form.html'
    success_url = reverse_lazy('catalog:products')
    login_url = 'users:login'
    redirect_field_name = "redirect_to"

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if (user.has_perm('catalog.can_edit_publication')
                and user.has_perm('catalog.can_edit_description')
                and user.has_perm('catalog.can_edit_category')):
            return ProductModeratorForm
        raise PermissionDenied("У вас нет прав для редактирования этого продукта.")


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление продукта."""
    model = Product
    success_url = reverse_lazy('catalog:products')

    login_url = 'users:login'
    redirect_field_name = "redirect_to"


class CatalogTemplateView(TemplateView):
    """Шаблон каталога."""
    template_name = 'catalog/base.html'


class ContactCreateView(CreateView):
    """Добавление нового контакта."""
    model = Contact
    template_name = 'catalog/contacts.html'
    fields = ['name', 'phone', 'message']
    success_url = '/products/'


class BlogListView(ListView):
    """Список блогов."""
    model = Blog
    fields = ('title', 'text', 'preview', 'created_at', 'publication')
    success_url = reverse_lazy('blog:blog')

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogDetailView(DetailView):
    """Подробная информация о блоге."""
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    """Добавление нового блога."""
    model = Blog
    fields = ['title', 'text', 'preview', 'publication']
    success_url = reverse_lazy('catalog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    """Редактирование блога."""
    model = Blog
    fields = ['title', 'text', 'preview', 'publication']

    def get_success_url(self):
        return reverse_lazy('catalog:blog_detail', kwargs={'pk': self.object.pk})


class BlogDeleteView(DeleteView):
    """Удаление блога."""
    model = Blog
    success_url = reverse_lazy('catalog:blog')

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<header>
    {% include 'catalog/includes/inc_menu.html' %}
</header>

<main>

{% include 'catalog/includes/inc_section.html' %}

{% block content %}{% endblock %}
</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#" style="color: green;">Наверх</a>
    </p>
    <p class="mb-1">&copy; {% now "Y" %}</p>
  </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    </body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row d-flex justify-content-center align-items-center" style="height: 5vh;">
        <div class="row">
            <div class="col-5 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            <p class="text-center">Хотите удалить "{{object.title}}"?</p>
                            <div class="d-flex flex-column justify-content-center">
                                <button type="submit" class="btn btn-outline-danger mb-3">Подтвердить</button>
                                <a class="btn btn-outline-success" href="{% url 'catalog:blog' %}" role="button">Назад</a>
                            </div>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}{{ blog.title }}{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{blog.preview | media_filter}}" >
            <div class="card-body">
              <p class="card-text">{{ blog.text }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'catalog:blog_update' blog.pk %}" class="btn btn-outline-success">Редактировать</a>
                    <a href="{% url 'catalog:blog_delete' blog.pk %}" class="btn btn-outline-danger">Удалить</a>
                </div>
                <small class="text-body-secondary">{{ blog.created_at }}</small>
              </div>
              <div>
                <small class="text-body-secondary">{{ blog.slug }}</small>
              </div>
              <div>
                <a href="{% url 'catalog:blog' %}" class="btn btn-outline-success">Назад</a>
              </div>
            </div>
          </div>
        </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row d-flex justify-content-center align-items-center" style="height: 100vh;">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method='post' enctype="multipart/form-data" >
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                            <a class="btn btn-outline-danger" href="{% url 'catalog:blog' %}" role="button">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row d-flex justify-content-center mb-3">
        <div class="col-auto">
          <a href="{% url 'catalog:blog_create' %}" class="btn btn-outline-success">Создать блог</a>
        </div>
      </div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for blog in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{blog.preview | media_filter}}" >
            <div class="card-body">
              <p class="card-text">{{blog.title}}</p>
              <p class="card-text">{{blog.number_of_views}}</p>
              <p class="card-text">{{ blog.text | slice_by_space:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'catalog:blog_detail' blog.pk %}" type="button" class="btn btn-outline-success">Посмотреть</a>
                </div>
                <small class="text-body-secondary">{{blog.created_at}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
  <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for category in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <p class="card-text">{{ category.name }}</p>
              <p class="card-text">{{ category.description }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block title %}Контакты{% endblock %}
{% block content %}
<body>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-outline-success">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row d-flex justify-content-center align-items-center" style="height: 5vh;">
        <div class="row">
            <div class="col-5 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            <p class="text-center">Хотите удалить "{{object.title}}"?</p>
                            <div class="d-flex flex-column justify-content-center">
                                <button type="submit" class="btn btn-outline-danger mb-3">Подтвердить</button>
                                <a class="btn btn-outline-success" href="{% url 'catalog:products' %}" role="button">Назад</a>
                            </div>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{product.image | media_filter}}" >
            <div class="card-body">
              <p class="card-text">{{ product.description }}</p>
              <p class="card-text">
                <span class="badge bg-success">Активная версия: {{ product.active_version }}</span>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if perms.catalog.can_edit_publication and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == product.owner %}
                  <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-outline-success">Изменить</a>
                  {% endif %}
                  {% if user == product.owner or user.is_superuser %}
                  <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-outline-danger">Удалить</a>
                  {% endif %}
                  <a href="/products" class="btn btn-outline-success">Назад</a>
                </div>
                <small class="text-body-secondary">{{ product.price }} руб.</small>
              </div>
            </div>
          </div>
        </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12 px-5">
        <div class="row d-flex justify-content-center " style="height: 100vh;">
            <div class="col-6 px-3">
                <div class="card">
                    <div class="card-body">
                        <form method='post' enctype="multipart/form-data" >
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-outline-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                            <a class="btn btn-outline-danger" href="{% url 'catalog:products' %}" role="button">Отменить</a>
                    </div>
                </div>
            </div>
            <div class="col-6 px-3">
                <div class="card">
                    <p class="card-text text-center mt-3">Дополнительная информация(версия)</p>
                    <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% endfor %}
                        </form>
                    </div>

                </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
  <div class="d-flex justify-content-center mt-4 mb-4">
    <a href="{% url 'catalog:product_create' %}" class="btn btn-outline-success">Создать продукт</a>
  </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{product.image | media_filter}}" >
            <div class="card-body">
              <p class="card-text">{{product.name}}</p>
              <p class="card-text">{{product.category}}</p>
              <p class="card-text">{{ product.description | slice_by_space:100 }}</p>
              <p class="card-text">
                <span class="badge bg-success">Активная версия: {{ product.active_version }}</span>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'catalog:product_detail' product.pk %}" type="button" class="btn btn-outline-success">Узнать больше</a>
                  {% if perms.catalog.can_edit_publication and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == product.owner %}
                  <a href="{% url 'catalog:product_update' product.pk %}" type="button" class="btn btn-outline-success">Изменить</a>
                  {% endif %}
                </div>
                <small class="text-body-secondary">{{product.price}} руб.</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}